version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
        - 8081:8080
    volumes:
        - ./src/api:/go/src/github.com/shinjiezumi/go-todo-api
        - /go/src/github.com/shinjiezumi/go-todo-api/vendor
    environment:
      TZ: Asia/Tokyo
    tty:
      true
    command: gin -i -p 8080 run
  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./src/front:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm run serve
