version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    depends_on:
      - db
    ports:
        - 8081:8080
    volumes:
      - ./src/api:/go/src
    environment:
      TZ: Asia/Tokyo
    command: gin -i -p 8080 run
    tty:
      true
  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./src/front:/app
    command: npm run serve
    stdin_open: true
    tty: true
  db:
    build: docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
  docs:
    build:
      context: .
      dockerfile: docker/docs/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src/api/docs:/docs
    command: aglio -i /docs/api.md -s -h 0.0.0.0
