FROM golang:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    zip \
    unzip \
    iputils-ping \
    vim

ENV GIN_MODE=release

COPY ./src/api /go/src/github.com/shinjiezumi/go-todo-api

WORKDIR /go/src/github.com/shinjiezumi/go-todo-api

RUN go get -u github.com/codegangsta/gin \
  && go get -u github.com/golang/dep/cmd/dep \
  && dep ensure